services:
  learning-platform:
    build:
      context: .
      dockerfile: apps/learning-platform/Dockerfile
    container_name: learning-platform
    ports:
      - "4001:4000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    restart: unless-stopped
